name: cli-yargs-countentriesindirectory

on:
  push:
    paths:
      - 'cli/yargs/countEntriesInDirectory/**'
  pull_request:
    paths:
      - 'cli/yargs/countEntriesInDirectory/**'
  schedule:
    # Every day at 1am
    - cron: '0 1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest  # Static OS value (ubuntu-latest)
    env:
      CI: true
    steps:
      - uses: actions/checkout@v2  # Checkout code from repository
      - name: Use Node.js 12.x  # Static Node.js version (12.x)
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'  # Hardcoded Node.js version 12.x
      - name: Install dependencies
        run: npm install  # Install dependencies using npm
        working-directory: './cli/yargs/countEntriesInDirectory'  # Path to the app directory
      # - name: Run tests
      #   run: npm run test  # Run tests defined in package.json
      #   working-directory: './cli/yargs/countEntriesInDirectory'  # Path to the app directory

  stage:
    runs-on: ubuntu-latest  # Static OS value (ubuntu-latest)
    env:
      CI: true
    steps:
      - uses: actions/checkout@v2  # Checkout code from repository
      - name: Use Node.js 12.x  # Static Node.js version (12.x)
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'  # Hardcoded Node.js version 12.x
      - name: Install dependencies
        run: npm install  # Install dependencies using npm
        working-directory: './cli/yargs/countEntriesInDirectory'  