name: servers-express-api-with-express-and-handlebars

on:
  push:
    paths:
      - 'servers/express/api-with-express-and-handlebars/**'
  pull_request:
    paths:
      - 'servers/express/api-with-express-and-handlebars/**'
  schedule:
    # Every day at 1am
    - cron: '0 1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest  # Static OS value (ubuntu-latest)
    env:
      CI: true
    steps:
      - uses: actions/checkout@v2  # Checkout code from repository
      - name: Use Node.js 12.x  # Static Node.js version (12.x)
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'  # Hardcoded Node.js version
      - name: Install dependencies
        run: npm install  # Install dependencies using npm
        working-directory: './servers/express/api-with-express-and-handlebars'  # Path to the app directory
      - name: Run tests
        run: npm test  # Run tests defined in package.json
        working-directory: './servers/express/api-with-express-and-handlebars'  # Path to the app directory
